image: mingc/android-build-box:latest

stages:
  - lint
  - test
  - development
  - release

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

# Define a global cache
cache:
  key: gradle-cache-key
  paths:
    - .gradle/wrapper
    - .gradle/caches

# Kotlin lint check
# Check linting
kotlinLint:
  interruptible: false
  stage: lint
  script:
    - ./gradlew ktlintCheck --continue

# Run tests
runTests:
  interruptible: false
  stage: test
  script:
    - ./gradlew clean connectedCheck

# Assemble debug build for dev flavor
publishDevDebug:
  interruptible: true
  stage: development
  script:
    - ./gradlew assembleDevDebug
    - mv app/build/outputs/apk/dev/debug/app-dev-debug.apk ./
  artifacts:
    name: "IpScanner-$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./app-dev-debug.apk
    expire_in: 1 day

# Run master branch assembly for dev release candidate.
publishDevRelease:
  interruptible: false
  stage: release
  script:
    - ./gradlew assembleDevRelease
    - mv app/build/outputs/apk/dev/release/app-dev-release.apk ./
  artifacts:
    name: "IpScanner-$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
        - ./app-dev-release.apk
  only:
    - main