image: jangrewe/gitlab-ci-android

stages:
  - lint
  - build
  - release

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

# Kotlin lint check
# Check linting
kotlinLint:
  interruptible: false
  stage: lint
  script:
    - ./gradlew ktlintCheck --continue

# Assemble debug build for dev flavor
assembleDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew assembleDevDebug
  artifacts:
    paths:
      - app/build/outputs/dev/debug

# Run master branch assembly for dev release candidate.
devRelease:
  interruptible: false
  stage: release
  script:
    - ./gradlew assembleDevRelease
  artifacts:
    paths:
      - app/build/outputs/dev/release
  only:
    - master