image: jangrewe/gitlab-ci-android

stages:
  - lint
  - build
  - release

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

# Start caching gradle dependencies and wrapper
buildCache:
  stage: build
  script:
    - ./gradlew assemble
  only:
    changes:
      - "*.gradle"
      - gradle.properties
  cache:
    key: gradle-cache-key
    paths:
      - .gradle/wrapper
      - .gradle/caches
    policy: push

# Define a global cache
cache:
  key: gradle-cache-key
  paths:
    - .gradle/wrapper
    - .gradle/caches
  policy: pull


# Kotlin lint check
# Check linting
kotlinLint:
  interruptible: false
  stage: lint
  script:
    - ./gradlew ktlintCheck --continue

# Assemble debug build for dev flavor
publishDevDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew assembleDevDebug
    - mv app/build/outputs/apk/dev/debug/app-dev-debug.apk ./
  artifacts:
    name: "IpScanner-$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./app-dev-debug.apk
    expire_in: 1 day

# Run master branch assembly for dev release candidate.
publishDevRelease:
  interruptible: false
  stage: release
  script:
    - ./gradlew assembleDevRelease
  artifacts:
    paths:
      - app/build/outputs/
  only:
    - main