image: jangrewe/gitlab-ci-android

stages:
  - lint
  - build
  - release

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

# Kotlin lint check
# Check linting
kotlinLint:
  interruptible: false
  stage: lint
  script:
    - ./gradlew ktlintCheck --continue

# Assemble debug build for dev flavor
publishDevDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew assembleDevDebug
  artifacts:
    paths:
      - app/build/outputs/apk/dev/debug/app-dev-debug.apk
    expire_in: 1 day

# Run master branch assembly for dev release candidate.
publishDevRelease:
  interruptible: false
  stage: release
  script:
    - ./gradlew assembleDevRelease
  artifacts:
    paths:
      - app/build/outputs/
  only:
    - main